defaults: &defaults
  adapter: postgresql
  template: template0
  
test:
  <<: *defaults
  database: "stm_test"

development:
  <<: *defaults
  database: "stm_dev"

production:
  <<: *defaults
  database: "stm_production"